apiVersion: v1
kind: Namespace
metadata:
  name: statsee
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashboard-db
  namespace: statsee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: statsee
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: ghcr.io/centerionware/statsee:latest
          env:
            - name: NET_IFACE
              value: enp0s6
              -name: HOST_PROC
              value: /host/proc
              -name: HOST_SYS
              value: /host/sys
              -name: HOST_ETC
              value: /host/etc
              -name: HOST_VAR
              value: /host/var
              -name: HOST_RUN
              value: /host/run
              -name: HOST_DEV
              value: /host/dev
              -name: HOST_ROOT
              value: /host/root
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: etc
              mountPath: /host/etc
              readOnly: true
            - name: var
              mountPath: /host/var
              readOnly: true
            - name: run
              mountPath: /host/run
              readOnly: true
            - name: dev
              mountPath: /host/dev
              readOnly: true
            - name: root
              mountPath: /host/root
              readOnly: true
            - name: db
              mountPath: /db
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
        - name: var
          hostPath:
            path: /var
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: root
          hostPath:
            path: /
        - name: db
          persistentVolumeClaim:
            claimName: dashboard-db
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: statsee
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: statsee
spec:
  selector:
    app: dashboard
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP